const state = { token: localStorage.getItem('lampai_token') || '', demo: false, actor: null, dashboard: null, announcements: [], view: 'dashboard', editing: null };
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const thaiDate = (value) => value ? new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '—';
const statusLabel = {draft:'ร่าง',published:'เผยแพร่แล้ว',active:'กำลังดำเนินการ',updated:'มีการอัปเดต',resolved:'ปิดเรื่องแล้ว',expired:'หมดอายุ',archived:'เก็บถาวร',queued:'รอส่ง',sent:'ส่งแล้ว',failed:'ส่งไม่สำเร็จ',skipped:'ข้าม'};
const typeLabel = {notice:'ประกาศ',meeting:'ประชุม',event:'กิจกรรม',news:'ข่าว',road:'ถนน',utility:'สาธารณูปโภค',health:'สุขภาพ',official:'ราชการ'};
const priorityLabel = {critical:'ด่วนที่สุด',important:'สำคัญ',normal:'ปกติ',info:'ข้อมูล'};
function showNotice(message, bad = false) { const el = $('#notice'); el.textContent = message; el.className = `notice${bad ? ' bad' : ''}`; setTimeout(() => el.classList.add('hidden'), 4200); }
async function api(path, options = {}) { const headers = {'content-type':'application/json', ...(options.headers || {})}; if (state.token) headers.authorization = `Bearer ${state.token}`; const res = await fetch(path, {...options, headers}); const body = await res.json().catch(() => ({})); if (!res.ok) throw new Error(body.error || 'เกิดข้อผิดพลาด'); return body; }
function showLogin() { $('#login-view').classList.remove('hidden'); $('#app-view').classList.add('hidden'); }
function showApp() { $('#login-view').classList.add('hidden'); $('#app-view').classList.remove('hidden'); $('#mode-badge').textContent = state.demo ? 'โหมดสาธิต' : 'เชื่อมต่อ Supabase'; $('#user-role').textContent = state.actor ? `สิทธิ์: ${state.actor.role}` : ''; }
async function boot() { try { const config = await api('/api/auth/config'); state.demo = config.demo; if (!state.demo && !state.token) return showLogin(); const me = await api('/api/me'); state.actor = me.actor; showApp(); await loadData(); } catch (error) { if (!state.demo) { state.token = ''; localStorage.removeItem('lampai_token'); showLogin(); $('#login-error').textContent = error.message; } else { showLogin(); $('#login-error').textContent = error.message; } } }
async function loadData() { const data = await api('/api/dashboard'); state.dashboard = data; state.announcements = (await api('/api/announcements')).announcements; render(); }
function render() { renderDashboard(); renderAnnouncements(); renderDeliveries(); renderJobs(); document.querySelectorAll('.view').forEach((el) => el.classList.toggle('hidden', el.id !== `view-${state.view}`)); document.querySelectorAll('.tab').forEach((el) => el.classList.toggle('active', el.dataset.view === state.view)); }
function renderDashboard() { const d = state.dashboard; if (!d) return $('#view-dashboard').innerHTML = '<div class="spinner">กำลังโหลดข้อมูล…</div>'; const c = d.counts; const recent = d.announcements || []; $('#view-dashboard').innerHTML = `<div class="cards"><div class="card teal"><span class="label">ประกาศทั้งหมด</span><span class="value">${c.total}</span></div><div class="card"><span class="label">ร่างรอเผยแพร่</span><span class="value">${c.draft}</span></div><div class="card"><span class="label">กำลังดำเนินการ</span><span class="value">${c.active}</span></div><div class="card"><span class="label">คิวรอส่ง</span><span class="value">${c.queued}</span></div><div class="card"><span class="label">ส่งไม่สำเร็จ</span><span class="value">${c.failed}</span></div></div><div class="grid-2"><div class="panel"><div class="panel-heading"><h2>ประกาศที่เปลี่ยนแปลงล่าสุด</h2><a href="#" data-goto="announcements">ดูทั้งหมด</a></div>${recent.length ? recent.map(announcementRow).join('') : '<div class="empty">ยังไม่มีประกาศ</div>'}</div><div><div class="panel weather"><div class="panel-heading"><h2>อากาศล่าสุด</h2><span class="badge">Open-Meteo</span></div>${d.weather ? `<div class="weather-value">${d.weather.temperatureC ?? '—'}°C</div><p class="muted">ลม ${d.weather.windKmh ?? '—'} กม./ชม. · ฝน ${d.weather.precipitationMm ?? '—'} มม.</p><p class="row-meta">เก็บข้อมูล ${thaiDate(d.weather.observedAt)}</p>` : '<div class="empty">ยังไม่มีข้อมูลอากาศ</div>'}</div><div class="panel"><div class="panel-heading"><h2>งานระบบล่าสุด</h2><a href="#" data-goto="jobs">ดูทั้งหมด</a></div>${(d.jobs || []).slice(0,4).map(jobRow).join('') || '<div class="empty">ยังไม่มีประวัติงาน</div>'}</div></div></div>`; document.querySelectorAll('[data-goto]').forEach((el) => el.addEventListener('click', (e) => { e.preventDefault(); state.view = el.dataset.goto; render(); })); }
function announcementRow(a) { return `<div class="announcement-row"><span class="dot ${a.priority}"></span><div class="row-main"><p class="row-title">${escapeHtml(a.title)}</p><p class="row-meta">${typeLabel[a.type] || a.type} · ${priorityLabel[a.priority] || a.priority} · แก้ไข ${thaiDate(a.updatedAt)}</p></div><span class="status ${a.status}">${statusLabel[a.status] || a.status}</span></div>`; }
function renderAnnouncements() { const rows = state.announcements || []; $('#view-announcements').innerHTML = `<div class="panel"><div class="panel-heading"><div><h2>ประกาศทั้งหมด</h2><p class="muted">สร้างร่าง แก้ไข และเผยแพร่เมื่อผ่านการตรวจ</p></div><button class="primary" id="new-from-list">+ สร้างประกาศ</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ประกาศ</th><th>ประเภท</th><th>ความสำคัญ</th><th>สถานะ</th><th>แก้ไขล่าสุด</th><th></th></tr></thead><tbody>${rows.length ? rows.map((a) => `<tr><td><strong>${escapeHtml(a.title)}</strong><br><span class="row-meta">${escapeHtml(a.location || 'ไม่ระบุสถานที่')}</span></td><td>${typeLabel[a.type] || a.type}</td><td>${priorityLabel[a.priority] || a.priority}</td><td><span class="status ${a.status}">${statusLabel[a.status] || a.status}</span></td><td>${thaiDate(a.updatedAt)}</td><td><div class="actions">${a.status === 'draft' ? `<button class="small-btn" data-edit="${a.id}">แก้ไข</button>` : ''}${['draft','published','active','updated'].includes(a.status) && ['admin','village_head'].includes(state.actor?.role) ? `<button class="small-btn" data-publish="${a.id}">${a.status === 'draft' ? 'เผยแพร่' : 'ดูแล'}</button>` : ''}${['published','active','updated'].includes(a.status) && ['admin','village_head'].includes(state.actor?.role) ? `<button class="small-btn danger" data-resolve="${a.id}">ปิดเรื่อง</button>` : ''}</div></td></tr>`).join('') : '<tr><td colspan="6"><div class="empty">ยังไม่มีประกาศ</div></td></tr>'}</tbody></table></div></div>`; $('#new-from-list').addEventListener('click', () => openForm()); document.querySelectorAll('[data-edit]').forEach((el) => el.addEventListener('click', () => openForm(el.dataset.edit))); document.querySelectorAll('[data-publish]').forEach((el) => el.addEventListener('click', () => publishAnnouncement(el.dataset.publish))); document.querySelectorAll('[data-resolve]').forEach((el) => el.addEventListener('click', () => resolveAnnouncement(el.dataset.resolve))); }
function renderDeliveries() { const rows = state.dashboard?.deliveries || []; $('#view-deliveries').innerHTML = `<div class="panel"><div class="panel-heading"><div><h2>สถานะการส่ง LINE</h2><p class="muted">รายการล่าสุด โดยไม่แสดงเนื้อหาข้อความใน dashboard</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ประเภท</th><th>ความสำคัญ</th><th>สถานะ</th><th>ครั้งที่ลอง</th><th>สร้างเมื่อ</th><th>ข้อผิดพลาด</th></tr></thead><tbody>${rows.length ? rows.map((d) => `<tr><td>${d.kind === 'briefing' ? 'สรุปประจำวัน' : 'ประกาศ'}</td><td>${priorityLabel[d.priority] || d.priority}</td><td><span class="status ${d.status}">${statusLabel[d.status] || d.status}</span></td><td>${d.attemptCount}</td><td>${thaiDate(d.createdAt)}</td><td class="row-meta">${escapeHtml(d.lastError || '—')}</td></tr>`).join('') : '<tr><td colspan="6"><div class="empty">ยังไม่มีรายการส่ง</div></td></tr>'}</tbody></table></div></div>`; }
function jobRow(j) { return `<div class="announcement-row"><span class="dot ${j.status === 'error' ? 'critical' : ''}"></span><div class="row-main"><p class="row-title">${escapeHtml(j.job)}</p><p class="row-meta">${thaiDate(j.startedAt)}</p></div><span class="status ${j.status === 'ok' ? 'sent' : j.status === 'error' ? 'failed' : 'queued'}">${j.status === 'ok' ? 'สำเร็จ' : j.status === 'error' ? 'ล้มเหลว' : 'กำลังทำงาน'}</span></div>`; }
function renderJobs() { const rows = state.dashboard?.jobs || []; $('#view-jobs').innerHTML = `<div class="panel"><div class="panel-heading"><div><h2>ประวัติงานระบบ</h2><p class="muted">ติดตาม scheduler, briefing, dispatch และ healthcheck</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>งาน</th><th>เริ่มเมื่อ</th><th>เสร็จเมื่อ</th><th>สถานะ</th><th>สถิติ</th><th>ข้อผิดพลาด</th></tr></thead><tbody>${rows.length ? rows.map((j) => `<tr><td><strong>${escapeHtml(j.job)}</strong></td><td>${thaiDate(j.startedAt)}</td><td>${thaiDate(j.finishedAt)}</td><td><span class="status ${j.status === 'ok' ? 'sent' : j.status === 'error' ? 'failed' : 'queued'}">${j.status === 'ok' ? 'สำเร็จ' : j.status === 'error' ? 'ล้มเหลว' : 'กำลังทำงาน'}</span></td><td class="row-meta">${escapeHtml(JSON.stringify(j.stats || {}))}</td><td class="row-meta">${escapeHtml(j.error || '—')}</td></tr>`).join('') : '<tr><td colspan="6"><div class="empty">ยังไม่มีประวัติงาน</div></td></tr>'}</tbody></table></div></div>`; }
function formHtml(a = {}) { return `<div class="panel"><div class="panel-heading"><div><h2>${a.id ? 'แก้ไขร่างประกาศ' : 'สร้างประกาศใหม่'}</h2><p class="muted">ทุกประกาศเริ่มเป็นร่างและยังไม่ส่งออกจนกว่าจะกดเผยแพร่</p></div></div><form id="announcement-form" class="stack"><div class="form-grid"><label>หัวข้อประกาศ *<input name="title" required value="${escapeHtml(a.title || '')}" placeholder="เช่น แจ้งปิดถนนชั่วคราว"></label><label>ประเภท<select name="type">${Object.entries(typeLabel).map(([k,v]) => `<option value="${k}" ${a.type === k ? 'selected' : ''}>${v}</option>`).join('')}</select></label></div><label>รายละเอียด<textarea name="body" placeholder="เขียนเฉพาะข้อมูลที่ยืนยันแล้ว">${escapeHtml(a.body || '')}</textarea></label><div class="form-grid"><label>สถานที่<input name="location" value="${escapeHtml(a.location || '')}" placeholder="เช่น ศาลาหมู่บ้าน"></label><label>ความสำคัญ<select name="priority">${Object.entries(priorityLabel).map(([k,v]) => `<option value="${k}" ${a.priority === k ? 'selected' : ''}>${v}</option>`).join('')}</select></label></div><div class="form-grid"><label>เริ่มเมื่อ<input name="effectiveFrom" type="datetime-local" value="${a.effectiveFrom ? new Date(a.effectiveFrom).toISOString().slice(0,16) : ''}"></label><label>สิ้นสุดเมื่อ<input name="effectiveTo" type="datetime-local" value="${a.effectiveTo ? new Date(a.effectiveTo).toISOString().slice(0,16) : ''}"></label></div><label>ระดับข้อมูล<select name="dataLevel"><option value="public" ${a.dataLevel !== 'internal' && a.dataLevel !== 'sensitive' ? 'selected' : ''}>สาธารณะ</option><option value="internal" ${a.dataLevel === 'internal' ? 'selected' : ''}>ภายใน</option><option value="sensitive" ${a.dataLevel === 'sensitive' ? 'selected' : ''}>อ่อนไหว</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancel-form">ยกเลิก</button><button type="submit" class="primary">บันทึกร่าง</button></div></form></div>`; }
function openForm(id = null) { state.editing = id ? state.announcements.find((a) => a.id === id) : null; state.view = 'announcements'; $('#view-announcements').innerHTML = formHtml(state.editing || {}); render(); const host = $('#view-announcements'); host.innerHTML = formHtml(state.editing || {}); $('#cancel-form').addEventListener('click', () => { state.editing = null; renderAnnouncements(); }); $('#announcement-form').addEventListener('submit', saveAnnouncement); }
async function saveAnnouncement(event) { event.preventDefault(); const form = new FormData(event.target); const data = Object.fromEntries(form.entries()); try { if (state.editing) await api(`/api/announcements/${state.editing.id}`, {method:'PATCH',body:JSON.stringify(data)}); else await api('/api/announcements', {method:'POST',body:JSON.stringify(data)}); state.editing = null; await loadData(); showNotice('บันทึกร่างประกาศแล้ว'); } catch (error) { showNotice(error.message, true); } }
function deliveryNotice(d, base) {
  if (!d) return base + ' — จะแจ้งในสรุปข่าวรอบถัดไป';
  if (!d.configured) return base + ' — ยังไม่ได้ตั้งค่า LINE ข้อความรอในคิว';
  if (d.sent > 0) return base + ' และส่งเข้า LINE แล้ว';
  if (d.timedOut) return base + ' — กำลังส่งเข้า LINE (ระบบจะส่งซ้ำให้อัตโนมัติถ้าไม่สำเร็จ)';
  return base + ' — ส่งเข้า LINE ไม่สำเร็จ ระบบจะลองใหม่อัตโนมัติ' + (d.error ? ' (' + d.error + ')' : '');
}
async function publishAnnouncement(id) { if (!confirm('ยืนยันเผยแพร่ประกาศนี้?')) return; try { const r = await api(`/api/announcements/${id}/publish`, {method:'POST'}); await loadData(); showNotice(deliveryNotice(r.delivery, 'เผยแพร่ประกาศแล้ว')); } catch (error) { showNotice(error.message, true); } }
async function resolveAnnouncement(id) { const summary = prompt('เขียนข้อความสรุปการปิดเรื่อง'); if (!summary) return; try { const r = await api(`/api/announcements/${id}/resolve`, {method:'POST',body:JSON.stringify({summary})}); await loadData(); showNotice(deliveryNotice(r.delivery, 'ปิดเรื่องแล้ว')); } catch (error) { showNotice(error.message, true); } }
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); $('#login-error').textContent = ''; const data = Object.fromEntries(new FormData(event.target).entries()); try { const session = await api('/api/auth/login', {method:'POST',body:JSON.stringify(data)}); state.token = session.accessToken; localStorage.setItem('lampai_token', state.token); const me = await api('/api/me'); state.actor = me.actor; showApp(); await loadData(); } catch (error) { $('#login-error').textContent = error.message; } });
$('#logout').addEventListener('click', () => { state.token = ''; localStorage.removeItem('lampai_token'); showLogin(); });
$('#new-announcement').addEventListener('click', () => openForm());
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => { state.view = tab.dataset.view; render(); }));
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {});
boot();
